wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.10.8
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1698125623.197102
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.8
      5: 0.15.12
      8:
      - 1
      - 5
      13: linux-x86_64
